# Többváltozós analízis mérnöki alkalmazásai - 2. gyakorlat


## 1. feladat: Rendezés

Valósítsátok meg a tetszőleges rendezési algoritmust Python nyelven! Írjatok egy függvényt, amely elvégzi az algoritmust egy számokat tartalmazó listán, majd futtassátok le tesztként a [3,2,1,1,8,5,16] számsoron!


![kep1](https://i.imgur.com/fq0A8hx.gif)

In [10]:
#1. feladat: Buborékrendezés függvényt, és futtatása [3,2,1,1,8,5,16]-on.
szamok=[3,1,5,6,7,3,2,0]
def bubble(x):
    for i in range(len(x)-1,-1,-1):
        for j in range(i):
            if(x[j+1] < x[j]):
                a=x[j+1]
                x[j+1]=x[j]
                x[j]=a
bubble(szamok)
print(szamok)

[0, 1, 2, 3, 3, 5, 6, 7]


## Mátrixok a matematikában

Ha valamilyen kommutatív gyűrű elemeit - pl: valós, komplex számokat - $m$ sorba és $n$ oszlopba rendezzük, akkor tudjuk, hogy egy $m x n$-es mátrixról van szó. (első szám a soroké, második az oszlopoké!)

Múlt héten megtanultatok műveleteket végezni mátrixokkal, és megbeszéltetek néhány tulajdonságot. Mi ezen az órán kicsit kiterjesztjük az elképzeléseiteket arról, hogy mire is lehet használni ezeket a műveleteket, és megtanuljuk, hogy, 

## Mátrixok megismerése a Python-ban: a Numpy csomag

A python numpy csomagja az egyik leggyakrabban használt kiegészítő: matematikai könyvtárakat tartalmaz, amik nagyon nagy segítségére vannak bárkinek, aki komolyabb műveleteket szeretne végezni. A Numpy elég jól optimalizált is, így az olyan számításokat is megéri NumPyosítani, amik megoldhatók alap Pythonnal is.

## Numpy telepítése a környezetünkbe, importálás

In [2]:
import numpy as np

## Array-ok, tömbök

A numpy a vektorokat, a mátrixokat és magasabb rendű (2D+) mennyiségeket mind array-nak/tömbnek hívja. Ezekben ugyanolyan típusú elemek lehetnek csak - nem úgy, mint eddig a többi adattároló struktúránkban. Egy ilyen tömböt a következőképpen tölthetek fel elemekkel:

In [0]:
a = np.array([1,2,3]) #rank 1/1D-s array/tömb készítése listából

print(a)
print(type(a))
print(a.shape)
print(a[1])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
2


In [0]:
b = np.array([[2,3],[0,1],[3,3]])

print(b) #megmaradnak a határolók ugyanúgy
print(b.shape) #2x2re számítunk
print(b[0,1]) #először sor, utána oszlop, 0-tól indul, mint a listákban is
print(b[1]) #lehet részekre bontani

[[2 3]
 [0 1]
 [3 3]]
(3, 2)
3
[0 1]


In [0]:
#Előfordulhat, hogy egységmátrixra van szükségem.
egyseg=np.eye(3)
print(egyseg)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
#Vagy üresre
empty=np.zeros((2,3))
print(empty)

[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
#Esetleg egyesek/konstans/random
const=np.full((2,2,2),6.9)
print(const)
egyesek=np.ones((2,2))
print(egyesek)
dobokocka=np.random.random((3,3)) #véletlenszerű értékek 0-1 között

[[[6.9 6.9]
  [6.9 6.9]]

 [[6.9 6.9]
  [6.9 6.9]]]


In [5]:
#vektortként is ki tudom választani:
tombom=np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]]) #tyű, ez borzalmas! Hogy lehet ezt rövidebben?
tombom2=np.arange(16) #ez a default, 0,16,1 is lehetne!
#ez így még nem ok!
tombom2=tombom2.reshape(2,2,4) #úristen, de kényelmes!

print(tombom)
print(tombom.shape)

print(tombom2)
print(tombom2.shape)


print(tombom[1,1,1])
#[1,1,1,0,1] miért nem jó?
print(tombom[1,1,[0,1]])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)
13
[12 13]


In [0]:
#Slicing vagy szeletelés
a=tombom[:,:,1:-1]
print(a)
print(a.shape)

b=tombom[[1],[1],1:-1]
print(b.shape)
#slicing és indexing különbsége!!!

[[[ 1  2]
  [ 5  6]]

 [[ 9 10]
  [13 15]]]
[[13 15]]


In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row1=a[1,:]
row2=a[1:2,:]

print(row1, row1.shape)
print(row2, row2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [0]:
#Egyszerre is lehet használni a kettőt, pl: [:,[1,2],:] ->mit csinál?
#slice-oljátok ki tombom-ből a 2-vel osztható számokat, úgy, hogy a dimenzióját megartja!
c1=tombom[:,:,[0,2]]
print(c1)
#most 1d-be!
c2=tombom[0,0,[0,2]] #? csak soronként?
print(c2)
#Flatten! Szükségetek lesz rá a háziban...
c2=c1.flatten()
print(c2)

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]
[0 2]
[ 0  2  4  6  8 10 12 14]


In [3]:
#tetszőleges elemek kiválasztása tetszőleges sorból
a = np.array([[1,2], [3, 4], [5, 6]])
#indexelés vektorokkal dimenziónként
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
print(np.array(a[[0,1,2],[0,1,0]]))


[1 4 5]
[1 4 5]


In [3]:
#hogyan választanátok ki egy mátrix minden sorából egy elemet? Sokszor előfordul, hogy ilyen kell.
a=np.array([np.arange(16)])
a=a.reshape(4,4)
print(a)
print(a[np.arange(4), [0,1,2,3]])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]


In [4]:
#bool-os indexelés: feltételnek megfelelő elemek kiválasztása mátrixból.
bool_idx=(a>3)
print(bool_idx)
#1D-s array visszaadása, ahol a feltétel teljesül:
print(a[bool_idx])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 4  5  6  7  8  9 10 11 12 13 14 15]


### Adattípusok tömbökben

In [5]:
x = np.array([1, 2])  # nupmpy választ
y = np.array([1.0, 2.0])  # numpy választ
z = np.array([1, 2], dtype=np.int64)  #forceolok (szám=bitek száma)
print(type(x),type(y),type(z))
print (x.dtype, y.dtype, z.dtype)
konv=y.astype('int64')
print(konv.dtype)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
int64 float64 int64
int64


## Alapműveletek tömbökkel

Az alapműveleteket \\( (+,-,\div,*,\sqrt,a^n) \\), ha a +,-,/,* (!! Matlab mágusok, figyelem),np.sqrt(),**  operátorokkal jelöljük őket, elemenként végzi el a numpy. Ez a mátrixoknál tanult összeghez és diadikus szorzathoz hasonlít. 

In [6]:
a1=np.array([[1,1],[1,1]])
b=np.array([[1,2],[1,3]])
print(b+2*a1)

[[3 4]
 [3 5]]


In [7]:
#igazából bármilyen egyváltozós függvényt is elemenként értékel ki:
a2=np.sin(a1)
print(a2)

[[0.84147098 0.84147098]
 [0.84147098 0.84147098]]


In [8]:
import numpy as np
#lehet elemenként is műveletelni
a[np.arange(4), [0,1,2,3]]+=5
print(a)

[[ 5  1  2  3]
 [ 4 10  6  7]
 [ 8  9 15 11]
 [12 13 14 20]]


In [9]:
#dot: mindig skaláris szorzatot végez el (két vektorból sose lesz mátrix)
v = np.array([9,10])
w = np.array([11, 12])
print(w)
print(np.dot(v,w))
print(np.dot(v.T,w)) #hiába transzponálok

[11 12]
219
219


In [29]:
A=np.array([np.arange(4)]).reshape(2,2)
print(A.dot(v))

[10 48]


In [32]:
#Hogy adnátok össze egy mátrix elemeit?
sum_of_A=A.dot(np.array([1,1])).dot(np.array([1,1]))
print(sum_of_A)
A=A.T
print(A)

6
[[0 2]
 [1 3]]


In [31]:
#tele vagyunk hasznos függvényekkel - guglizzatok sokat!
print (np.sum(A))  # Teljes összeg
print (np.sum(A, axis=0))  # Minden oszlopra egyesével
print (np.sum(A, axis=1))  # Minden sorra egyesével

6
[2 4]
[1 5]


In [34]:
#broadcasting - mátrixok kiterjesztése, pl: vektort szeretnék hozzáadni egy mátrix minden sorához.
#x mátrix minden sorához hozzáadom v vektort, eltárolom y-ban.
x = np.array([np.arange(1,13)]).reshape(4,3)
v = np.array([1, 0, 1])
y = np.empty_like(x)   # ugyanolyan shape

# for ciklussal
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [36]:
#ez egy bazi nagy mátrixsznál nagyon lassú lenne. Mi lenne, ha gyorsan tudnék csinálni egy olyan mátrixot, amit csak
#össze kell adnom x-el az eredményhez?
vt=np.tile(v,(4,1))
print(vt)
y=x+vt
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [38]:
y=x+v
print(y)
#és ugyanúgy megcsilnálja! Itt olvassatok utána: 
#Dokumentáció: (http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)
#Magyarázat: (http://wiki.scipy.org/EricsBroadcastingDoc).

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [4]:
#előfordulhat, hogy fájlba kiírnátok/beolvasnátok:
A=np.array([[0,4],[1,2]])
B=np.linalg.inv(A)
np.save('ikszde',B)
print(np.load('ikszde.npy'))

[[-0.5   1.  ]
 [ 0.25  0.  ]]


In [3]:
#amivel talán már szívtatok első matek gyakorlaton: a determináns!
A = np.array([[3,2,5],[0,1,0],[2,2,2]])
print(np.linalg.det(A))
#miért ilyen?
#vmi ellenőrzőt tudunk mondani?
print(np.linalg.det(np.eye(4)))
#ami szintén segíthet: invertálás
B=np.linalg.inv(A) #nem 0 a det és kvadratikus->lesz inverze!
print(B)

-3.999999999999999
1.0
[[-0.5  -1.5   1.25]
 [ 0.    1.    0.  ]
 [ 0.5   0.5  -0.75]]


## Numerikus integrálás - gyors áttekintés

A műszaki életben nagyon gyakran fordul elő, hogy valamilyen mennyiséget integrálnunk kell (pl.: kondi feszültségéből a töltést, gyorsulásmérőből a megtett utat kinyerni). A legtöbb mennyiséget manapság digitálisan (azaz mintavételezve) mérjük, és valamilyen számítógéppel értékeljük ki: nézzük meg, hogy a számítógépeink hogy integrálnak! A numerikus integrálásól [itt](https://web.cs.elte.hu/blobs/diplomamunkak/bsc_matelem/2010/pasztor_nikolett.pdf) is olvashattok bővebben.

### A legegyszerűbb módszer:

Integráljuk a mért mennyiséget az idő mentén! Minden pillanatban ismerjük az idő értékét, és a mennyiségünket is. Közelítsük az integrált a mennyiség(idő) grafikon alatti területtel.

![img](http://spiff.rit.edu/classes/phys317/lectures/num_integ2/rect_integ.gif)

## 3. feladat

Valósítsuk meg kódban a szinusz függvény integrálását a $[0, 2\pi]$ intervallumon!

In [4]:
import numpy as np
num_of_pts=1000000

time=np.linspace(0,2*np.pi, num_of_pts)
sin_t=np.sin(time)
int_sin_t=0
prev_t=0
for t in range(0,num_of_pts):
    int_sin_t+=(time[t]-prev_t)*sin_t[t]
    prev_t=time[t]
    
print(int_sin_t)

-3.414475547304343e-14


In [5]:
# meg tudjuk csinálni máshogy is! Ha amúgy is np vektorokkal dolgozunk, miért ne dolgoznánk vektorműveletekkel?
num_of_pts=1000000

time=np.linspace(0,2*np.pi, num_of_pts)

#ha állandó a mintavételezési idő, ez fölösleges, de az óvatosság nem árt
time_shifted=np.insert(time, 0,0)
time_shifted=np.delete(time_shifted, num_of_pts-1)

dt=time-time_shifted
sin_t=np.sin(time)

int_sin_t=np.dot(sin_t, dt)

print(int_sin_t)
#ez sokkal gyorsabb

1.6653345369377348e-15


### Trapéz módszer

Ez csak a legegyszerűbb módszer, nem így szokták igazából csinálni. Sokkal pontosabb például trapézokkal, de ezt nem fogjuk leprogramozni, mert van hozzá egy klassz [könyvtár](https://docs.scipy.org/doc/numpy/reference/generated/numpy.trapz.html).

![img_trapez](http://spiff.rit.edu/classes/phys317/lectures/num_integ2/trap_integ.gif)

In [0]:
num_of_pts=1000000

time=np.linspace(0,2*np.pi, num_of_pts)
sin_t=np.sin(time)

int_sin_t=np.trapz(sin_t, time)
print(int_sin_t)

## Szűrés

A valóságban az adataink többsége nagyon zajos. Digitális módon megszűrhetjük az adatainkat, erre egy módszer a mozgó átlag/moving average. A mozgó átlag lényege, hogy a szűrt értéket a környezetében található szűretlen értékek átlaga adja meg.
![moving_avg](http://www.cyclify.com/wiki/images/thumb/4/4d/Moving-average-filter-simulation.gif/598px-Moving-average-filter-simulation.gif)

### Csináljunk zajos adatot!

Az eredeti szinuszfüggvényünkön egy felharmonikust, egy nagyobb frekvenciájú (de kisebb amplitúdójú) szinuszt helyezhetünk el.

In [0]:
#szűrjünk mozgó átlaggal!

def moving_avg(my_list, N):
    moving_avgs=[]
    cumulated_sums=[]
    cumulated_sum=0
    for i in range(0,len(my_list)):
        cumulated_sum+=my_list[i]
        cumulated_sums.append(cumulated_sum)
        if(i>N):
            moving_avg=(cumulated_sums[i]-cumulated_sums[i-N])/N
            moving_avgs.append(moving_avg)
        else:
            moving_avgs.append(my_list[i])
        
    return moving_avgs   

In [0]:
#pyplot
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(time,sin_t)

In [0]:
%matplotlib inline
plt.plot(time,signal)

In [0]:
%matplotlib inline
plt.plot(time,moving_avg(signal,30))
# konvolúció magyarázásánál majd megmutatom a beépített numpy megoldást is. 1D konvolúcióval csinálja!